version: '3'
services:
  wechat-spider:
    image: wechat-spider:latest
    build: .
    restart: always
    security_opt:
      - no-new-privileges:true
    command: ["wait-for-it", "mariadb:3306", "--", "python3", "./run.py"]
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
    volumes:
      - "./mitmproxy:/root/.mitmproxy"
      - "./config:/app/wechat-spider/config"
    environment:
      - WECHAT_MYSQL_HOST=mariadb
      - WECHAT_MYSQL_PORT=3306
      - WECHAT_MYSQL_DB=${WECHAT_MYSQL_DB:-test}
      - WECHAT_MYSQL_USER=${WECHAT_MYSQL_USER:-root}
      - WECHAT_MYSQL_PASSWD=${WECHAT_MYSQL_PASSWD:-}
      - WECHAT_REDIS_HOST=redis
      - WECHAT_REDIS_PORT=6379
      - WECHAT_REDIS_DB=0
      - WECHAT_REDIS_PASSWD=${WECHAT_REDIS_PASSWD:-}
    depends_on:
      - mariadb
      - redis
    links:
      - redis
      - mariadb
  redis:
    image: redis:3.2
    restart: always
  mariadb:
    image: bitnami/mariadb:10.5-debian-10
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_USER=${WECHAT_MYSQL_USER:-root}
      - MARIADB_ROOT_PASSWORD=${WECHAT_MYSQL_PASSWD:-changeme}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
